version: '2'
services:
  consumer:
    container_name: consumer
    build: .
    ports:
      - 8081:8081
    networks:
      - application-network

  producer:
    container_name: producer
    build: update-state-producer-service
    ports:
      - 8082:8082
    networks:
      - application-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - application-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
    networks:
      - application-network

networks:
  application-network:
    driver: bridge